### PR TITLE
Completed css-brochure-form challenge. - Sharon Tieu

### PR DESCRIPTION
**Pull request by sharon-tieu**
css-brochure-form challenge

### CODE REVIEW

**Comment by sharon-tieu** [comment]
I tried my best.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon, your form is too wide as compared to the example, please revise and submit a new screenshot with your revision

**Comment by sharon-tieu** [comment]
css-brochure-form

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Now your form is too narrow 👀

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-12 at 10 00 36 AM

**Review by codingcodymiller — APPROVED** [review]
Great work!!

**Pull request merged**
