### PR TITLE
Completed css-canvas-medical project. - Sharon Tieu

### PR DESCRIPTION
**Pull request by sharon-tieu**
https://user-images.githubusercontent.com/103021766/168953756-6f5ef89a-9ed5-4c17-b009-6c539fb020b3.mov

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon, your gif didn't show the header at all. Please take screenshots of your output so that I can easily examine it in full.

**Comment by sharon-tieu** [comment]
https://user-images.githubusercontent.com/103021766/169138979-534a8e63-7217-4834-b306-1fa69c730f01.mov

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-18 at 12 16 35 PM

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-18 at 8 08 25 PM
Screen Shot 2022-05-18 at 8 09 08 PM
Screen Shot 2022-05-18 at 8 09 19 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! Your links in the navbar are still underlined and not the correct color, please revise and submit a new screenshot with your revision.

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-23 at 12 28 45 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon, you have a **_bunch_** of individually named row classes. You should only have _one_ row class, and you would make additional classes for any special augments you need to do to that element. Layout classes are utility classes, which means they are made to be reused infinitely. Ifg you are naming them specifically for each situation, you are making a bunch of tools that are not reusable rather than one tool you can use over and over.

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-29 at 11 39 56 PM
Screen Shot 2022-05-29 at 11 40 05 PM

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-29 at 11 40 26 PM

**Comment by sharon-tieu** [comment]
https://user-images.githubusercontent.com/103021766/170932765-efaf3a85-a295-43ea-8bd0-7ebabbf57963.mov

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
