### PR TITLE
Completed css-two-column-layout exercise. - Sharon Tieu

### PR DESCRIPTION
**Pull request by sharon-tieu**
https://user-images.githubusercontent.com/103021766/168420446-c03059eb-2087-4559-8b9f-7a2afce03af2.mov

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! A few things:
1. The line spacing on your subheader in the first row and the text in each column of the second row does not match the example.
2. The images are too large as compared to the example.

Please revise and submit a new screenshot with your revision.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! I see that this is still in progress, just submitting a review so that I know when it gets updated 🤓

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-20 at 3 22 54 PM
Screen Shot 2022-05-20 at 3 22 39 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! You have multiple variants of a `row` class, you should only have one `row` class ruleset, and the only styling on it should be `display: flex`. Any additional behavior should be applied to additional utility classes or a semantic class for that specific element.

**Comment by sharon-tieu** [comment]
May you further clarify what you want me to change? Are you referring to how I shouldn't have four rows in total? I have a row for my heading, two rows for the body which I split into columns, and then a footer. 
I only have my body row the same class name which I assigned display: flex and justify-content: center. 

Or do you mean that I should change my row class names and also give utility or semantic classes to other rows as well.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! Almost all of your layout classes filling the role of `column` or `row` are individually named for certain sections. That is not how layout classes are meant to work. You should be making _one_ version of the `row` class and _one_ version of each column class for each size needed, and the class name should describe its size, not what it is being applied to. If you have any further questions on this, feel free to reach out.

**Comment by sharon-tieu** [comment]
Screen Shot 2022-05-24 at 6 52 03 AM


(Keeping this as a record. Update: I changed my code to have my body only in one singular row. Changes that need to be made: Icon must be repositioned to be next to text instead of on top.)

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! Just submitting a review so that I know when this is ready for review 🤓

**Comment by sharon-tieu** [comment]
css-two-column-layout exercise

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Sharon! The contents of your middle row with the four `column-half` elements is too wide as compared to the example, please revise and submit a new screenshot with your revision.

**Comment by sharon-tieu** [comment]
Screen Shot 2022-06-11 at 12 36 47 PM

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
